export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS'
export const NUEVA_CATEGORIA = 'NUEVA_CATEGORIA'
export const ACTUAL_CATEGORIA = 'ACTUAL_CATEGORIA'

export const LIBROS_CATEGORIA = 'LIBROS_CATEGORIA'
export const LIBRO_ACTUAL = 'LIBRO_ACTUAL'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESSION = 'CERRAR_SESSION'